### ISSUE TITLE
Next up row

### ISSUE THREAD

**Issue by raulfelix** [lifewithoutandy/warhol#1]
Implement the HTML/CSS for the next up row type. This should include image and imageless views as well as all responsive behaviour.

Need some clarification on what is clickable and the hover states for image/imageless views @jonnybrian

**Comment by jonnybrian** [comment]
@rcar1115 I'd say the whole space is clickable.

There is currently an alpha black gradient over the image which gradates from 40 to 60. Lets say on hover those values change to 30 to 50.
