### ISSUE TITLE
Integrate header carousel (content manageable) 

### ISSUE THREAD

**Issue by raulfelix** [lifewithoutandy/warhol#10]
The carousel will pull in posts that have been marked as elements that should appear on the homepage. The title and subtitle of the post will be used and the feature image.

There also needs to be one extra element which is a shop image. I may need you to give me an example of this so I can figure out how this gets managed too @jonnybrian.

**Comment by jonnybrian** [comment]
@rcar1115 I've added this as a separate issue https://github.com/lifewithoutandy/warhol/issues/43
