### ISSUE TITLE
click anywhere to close modal

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#101]
@rcar1115 can you implement click anywhere off the content panel to close modal? this applies to both gallery and instagram please mate

**Comment by raulfelix** [comment]
but not in the share and search modal?? are you sure @jonnybrian

**Comment by jonnybrian** [comment]
correct @rcar1115 sorry i forgot those were also modal.

**Comment by jonnybrian** [comment]
more snowflake.

**Comment by raulfelix** [comment]
hahaha bloody snowflake... What if you click on caption in gallery does it close? this is a bit fiddly because there are hidden elements such as images. Would you expect someone would know to close the modal by clicking anywhere? @jonnybrian

**Comment by jonnybrian** [comment]
@rcar1115 yes I do think this is an expected action. Not sure how this is working currently but i'd say the comment text is not active.

**Comment by raulfelix** [comment]
this is done @jonnybrian
