### ISSUE TITLE
Navigation layout

### ISSUE THREAD

**Issue by raulfelix** [lifewithoutandy/warhol#11]
Implement html/css for menu overlay. Include all responsive behavior required for the menu.

@jonnybrian a couple points to clarify:
- Does the overlay fill the entire screen?
- If not... is the overlay dismissed only when clicking the close link?
- Do the menu items sit centered vertically?

**Comment by jonnybrian** [comment]
I ummm'd and ahhh'd about whether the bg should fill the whole screen... in the end I decided not and gave it the height you see in the designs... it was one of those details I felt might become clearer once it was built. I don't want to have to make you do double work on this so for now proceed as per the design.

The overlay is dismissed only with the close button or selecting a menu option yes.

The primary links sit centred vertically yes. The secondary links sit in a centered group underneath. You have the open version in the 'LWA-Elements.sketch' file yes?

**Comment by raulfelix** [comment]
Thanks for clearing that up. 

Yep I have the sketch files so I can now proceed with the fireworks. Going from full screen to just the nav is not a huge change from CSS point of view so lets see how you feel when you have something to click around in :+1:
