### ISSUE TITLE
category header not accepting hex value

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#113]
I tried adding a colour other than black #000 but it didn't seem to work for me...

Can you investigate thanks @rcar1115

**Comment by raulfelix** [comment]
@jonnybrian works fine from what I can see. More info? Where did you try this (yardy or staging) for which category?

**Comment by jonnybrian** [comment]
Yardy on parties and bullshit

**Comment by raulfelix** [comment]
just changed it twice on that category and it works fine?? @jonnybrian

**Comment by jonnybrian** [comment]
woah thats weird... i tried a stack of different options and nothing worked except black... can you add #2D7BC8 in there for me then...

**Comment by raulfelix** [comment]
oooo maybe its permissions with the account you used?? maybe you are not an admin user. Added that colour

**Comment by jonnybrian** [comment]
thanks yeah... i'll check again tomorrow back at the office... wierd

**Comment by jonnybrian** [comment]
@rcar1115 i know what i was doing wrong... I hadn't been adding the hashtag... foolio.
