### ISSUE TITLE
refine search layout

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#119]
- ~~the font in the text field change to Apercu~~
- ~~remove date stamp from results~~
- ~~category font size smaller~~

**Comment by raulfelix** [comment]
@jonnybrian ready for review

Since I am a man of fine details....
- Should the images have a roll over?

**Comment by raulfelix** [comment]
- clear content on close
- add overlay
- remove border radius showing up on mobile only
