### ISSUE TITLE
category links on staging

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#126]
@rcar1115 seems like these category links have a weirdness in the URL... is this something you're aware of? 

http://staging.lifewithoutandy.com/staging/featured/tuesdays

**Comment by raulfelix** [comment]
Hey bud im not 100% sure at the moment how to get around this because there is a conflict with how expression engine is setup i.e it uses the same structure as wordpress and I cant fix it without killing the current site...

How critical is this from a staging point of view?

**Comment by jonnybrian** [comment]
if its only an issue on staging that will go for the live version then it's not a biggy...

**Comment by raulfelix** [comment]
It definitely wont be an issue when moved off staging... If i get time I will look at it
