### ISSUE TITLE
Improve performance of loading the inline gallery view

### ISSUE THREAD

**Issue by raulfelix** [lifewithoutandy/warhol#129]
How fast each image loads depends on the size of the file etc. so waiting for the first 2 or 3 as a rule is not really reliable. We will display the slider as soon as all measurements for the inline view is complete and then fade in each images whenever it loads.

**Comment by raulfelix** [comment]
the loading is much quicker now with spinners per frame. There may need to be a little refinement though please check it out @jonnybrian.

**Comment by jonnybrian** [comment]
![loading-screenshot](https://cloud.githubusercontent.com/assets/7110827/3633570/e181bcb2-0ee8-11e4-9e37-0ec02ab6570e.png)

@rcar1115 mate we have a slight issue here where the individual loaders are appearing behind the title. Can we keep hiding the title and arrows and buttons until at least the first three images have appeared?

**Comment by raulfelix** [comment]
the problem is images do not load in order. So if I wait for the first three to load you could end up waiting 5 mins anyway as they may load after others which are perhaps smaller in file size. So that is not a good solution to improve performance... @jonnybrian

**Comment by jonnybrian** [comment]
ok so maybe we alter the style of the wheel, if it is alpha 0.5 then at least it won't clash with the title...? @rcar1115 

This could be a universal change for all wheel's i think...

**Comment by raulfelix** [comment]
hmmm that would make the spinner loook grey/brown... @jonnybrian 
![screen shot 2014-07-19 at 1 02 26 pm](https://cloud.githubusercontent.com/assets/996002/3633694/32c3dcd8-0ef1-11e4-8b0b-a45df0f3dcd2.png)

**Comment by jonnybrian** [comment]
I know... not sure what else to suggest though...

**Comment by raulfelix** [comment]
Maybe no spinner for the first couple? Or only dim the first couple? @jonnybrian

**Comment by raulfelix** [comment]
ive hidden the first 2 spinners... see what you think I could also just dim the first 2 if you prefer... otherwise lets close this @jonnybrian
