### ISSUE TITLE
portrait tablet breakpoint refinement

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#132]
as i find the most broken bits I'll add them to this list @rcar1115 
- ~~modal instabinge~~
- ~~share view reflow buttons~~
- ~~inline gallery to reflect bp1~~
- ~~search results~~
- ~~remove home carousel arrows~~ 
- ~~bunch carousel indicators and move down (mobile too)~~

**Comment by jonnybrian** [comment]
Ive noticed a layout problem with post title on a news post on this breakpoint @rcar1115 check this page:

http://staging.lifewithoutandy.com/news/music/yeasayers-anand-wilder-wilder-maxwell-kardon/

can we make the title width wider? and then if necessary reduce the font size/line height.

**Comment by raulfelix** [comment]
I have updated that header width for this breakpoint @jonnybrian

**Comment by jonnybrian** [comment]
@rcar1115 yes way better... so far this seems to be their longest title and it fits nicely... word etc!

**Comment by raulfelix** [comment]
question... how much do you care about 7-inch tablets? @jonnybrian

**Comment by jonnybrian** [comment]
Are you referring to 600px portrait views? at this stage not a massive concern... but would be good to capture some of their worst failings... you have access to one I take it?

**Comment by raulfelix** [comment]
Yeah Google nexus7... its that in between area... Here is an example of the search modal view
![nexus7_search](https://cloud.githubusercontent.com/assets/996002/3633716/9b9aefe2-0ef3-11e4-8f2b-77d3953dd00b.png)

**Comment by jonnybrian** [comment]
ok so if thats 600px, its 599px where it switches to mobile huh? maybe that breakpoint should be 620 instead?

**Comment by raulfelix** [comment]
Yeah ill update and give it a go

**Comment by raulfelix** [comment]
that fixes the issues... @jonnybrian

**Comment by jonnybrian** [comment]
that seems enough for now... @rcar1115 im closing
