### ISSUE TITLE
Homepage carousel touch interaction

### ISSUE THREAD

**Issue by raulfelix** [lifewithoutandy/warhol#133]
Question/suggestion regarding the carousel interaction on touch devices. 

I was wondering what you thought about not auto playing the slideshow and instead just allowing the user to swipe through the images in the carousel. Instead of fading you would get the horizontal paging transition.

This would be better for performance especially on small devices.

**Comment by jonnybrian** [comment]
@rcar1115 so this would be only for specific breakpoints, or across them all?

Having played with the site more, especially with the poor connection we've had this past week, there are still to minor adjustments that are needed with the transition timings etc... lets go though this tomorrow.

**Comment by raulfelix** [comment]
This would be only for touch devices id say... but we can talk about it tomorrow and perhaps look at an example...
