### ISSUE TITLE
Implement backend search functionality 

### ISSUE THREAD

**Issue by raulfelix** [lifewithoutandy/warhol#14]
The search modal should submit terms via an Ajax request to the CMS and populate the results. 

Points to clarify @jonnybrian 
- Are the results paginated?
- When no results are returned a message should be shown saying "No results were found"?

**Comment by jonnybrian** [comment]
@rcar1115 ideally I'd like not to paginate the results but lazyload them say 20 at a time... thoughts?
and a "No results were found" message in the centre of the screen would be great. Same font as the titles of the posts.

**Comment by raulfelix** [comment]
@jonnybrian is the default WP search ok? This was never really considered in the scope or estimation so if you can give me your thoughts on what you expect the search to find we can see what can be done. There are plugins that can improve it but it requires more investigation and database considerations etc...
