### ISSUE TITLE
Add a button at end of gallery to go back to start of gallery.

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#141]
@rcar1115 to add the full description here:
- a 'back to start' btn will appear when the left arrow/left swipe is actioned
- after the final slide a 'back to start' and a next up will appear
- batch load 20 images at a time, each new batch is loaded from either a right arrow click or swipe right
- the applied to both inline and modal gallery views

**Comment by raulfelix** [comment]
How should this relate to the gallery thumbnails? There could be a case where the user selects an image beyond the batch loaded so does this mean thumbnails are also lazy loaded? @jonnybrian

**Comment by jonnybrian** [comment]
@rcar1115 pngs are in dropbox > jpgs > LWA-Gallery-v2.zip
