### ISSUE TITLE
select 'photos by' from contributors dropdown

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#142]
@rcar1115 if this is a big change, then we will quote on it... so the idea would then be to replace the open text fields with two drop downs, one for words by, one for photos by, and then when viewing each contributor, it will display from either...

**Comment by raulfelix** [comment]
Yeah this is a change that will have to be quoted on @jonnybrian

**Comment by jonnybrian** [comment]
@rcar1115 to clarify: a post can now have two different contributors associated with it. The article where the names are displayed will link to each respective contributor page, showing the posts they have contributed to.

One post can have two different contributors and show up in two different contributor pages.

**Comment by raulfelix** [comment]
The changes for this have been pushed to staging - http://staging.lifewithoutandy.com/staging please review @jonnybrian.

There is now a dropdown labeled "photos" with the list of contributors.
