### ISSUE TITLE
split Info and Contributors into two separate pages

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#143]
@rcar1115 and then modify main menu accordingly

**Comment by raulfelix** [comment]
@jonnybrian is there anything that needs to be to done to the contributors page on bp1 given that they have about 20 now... quite long?

**Comment by raulfelix** [comment]
Assuming we keep the "contributor" title too as it was on the info page @jonnybrian

**Comment by jonnybrian** [comment]
@rcar1115 yeah keep the title 'Contributors' and for now lets leave the bp1 view of the profile pics etc as they are... I can see ways to tighten things up but lets not fuss about it for now... thanks.

**Comment by raulfelix** [comment]
I have pushed these changes to staging - http://staging.lifewithoutandy.com/staging please review @jonnybrian
