### ISSUE TITLE
update main menu

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#144]
@rcar1115 when the decision has been made to split 'info', can you: 
- change to Party & Bullshit
- remove Shot By
- Make Shop big text and sit under News
- list Info and contributors side-by-side

**Comment by raulfelix** [comment]
i assume "Tuesdays without" becomes "Tuesday without" @jonnybrian

**Comment by jonnybrian** [comment]
Yes @rcar1115 and also Twentyfour becomes TwentyFour

**Comment by raulfelix** [comment]
This is all done except for the splitting up of info and contributors @jonnybrian
