### ISSUE TITLE
allow custom link for each sponsor logo on category page

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#146]
@rcar1115 so we need to allow them to link their logo. I want to make this a change request but if its a relatively simple addition can we just get it done?

link would target a new window.

**Comment by raulfelix** [comment]
As discussed this one I can just do but only cause I'm one heck of a guy

**Comment by raulfelix** [comment]
@jonnybrian There is now a free text field labeled "Sponsor link" on the category edit page where you can add a URL. This will wrap the logo only in category headers.

**Comment by jonnybrian** [comment]
Splendid!
