### ISSUE TITLE
add a subscribe to mailing list 

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#148]
@rcar1115 I'll have to supply you with a design for this. Totally my bad, I never saw this on their existing site so never included it in the original designs.

What do you need from them to link the form up?

**Comment by raulfelix** [comment]
It appears they use a design company blacksaltstudio as a service to register people to the newsletter. I need to know how that form is setup... if there is something specific running on the server or if it is just a static form action url that I can copy and add to your form design... @jonnybrian

**Comment by jonnybrian** [comment]
@rcar1115 I have added two new pages to the 'jpgs' folder in dropbox - Subscribe and Success

I'll leave it up to you how much fancyness you want to add to the form field in terms of focus and validation etc... happy to chat on that.

Thoughts?

**Comment by raulfelix** [comment]
With regards to focus on input field... We can change border color??

I'd say lets do a like for like with regards to validation... If it really needs to be improved then Id want a change request for that... but html5 validation should be enough for now anyway :)

**Comment by raulfelix** [comment]
I suppose where the subscribe links sits is yet to come @jonnybrian

**Comment by jonnybrian** [comment]
we will have a link in the main menu 'Subscribe' after info...

**Comment by raulfelix** [comment]
I have implemented the subscribe and success pages...@jonnybrian one thing that we will need to remember to do though is update the existing redirect url which is this: lifewithoutandy.com/contact/subscribe-thankyou to the new one which is this: lifewithoutandy.com/subscribed

**Comment by jonnybrian** [comment]
Great stuff bud...

@rcar1115 will this be once we switch it live you mean?

**Comment by raulfelix** [comment]
yeah once we go live. We need to login to the email campaign site and update that redirect. @jonnybrian
