### ISSUE TITLE
can we re-order the way contributors display?

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#149]

**Comment by raulfelix** [comment]
Best I can do here is add a free text field where you enter a number 1,2,3 .... on the user profile page

**Comment by raulfelix** [comment]
The user table now has an **Order** column and each user edit screen has a select dropdown called **display order**. This will allow you to define the order in which to display users @jonnybrian

**Comment by jonnybrian** [comment]
Really super!
