### ISSUE TITLE
can we change permissions of authors?

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#150]

**Comment by raulfelix** [comment]
So @jonnybrian to recap what we want:
- **Admins** can publish articles and do everything as it is now
- **Contributors** can create articles but not publish. They also cannot delete or edit once published?
- **Authors** are no longer needed

**Comment by jonnybrian** [comment]
Yes agreed... so check that contributors can add images as well as text @rcar1115

**Comment by raulfelix** [comment]
Ok so I have set contributors to be able to upload media and create posts. Only the **Administrator** and **Contributor** roles should thus be used. @jonnybrian

**Comment by jonnybrian** [comment]
Super!
