### ISSUE TITLE
Implement gallery back to start button

### ISSUE THREAD

**Issue by raulfelix** [lifewithoutandy/warhol#173]
- [x] Position the button and animate from left to right when activated.
- [x] Implement click event to return to start of image set

**Comment by jonnybrian** [comment]
@rcar1115 
- [x] the back to start button should disappear when you click/swipe right again...
- [x] i guess you havent finished the button position on mobile for the final slide?
- [x] the position of the button is not centred vertically or horiz at the mo, screenshot attached

![img_2972](https://cloud.githubusercontent.com/assets/7110827/3961810/37095c68-275c-11e4-9572-c2e7906bf42a.PNG)
