### ISSUE TITLE
Integrate a final slide to display the next post

### ISSUE THREAD

**Issue by raulfelix** [lifewithoutandy/warhol#174]

**Comment by raulfelix** [comment]
hey @jonnybrian 

For the image which is pulled in for the next post when there is no feature image set for the next  post are we doing the usual thing where we try and get an image from the content of the next post? I guess this would happen in the case where a news article has a gallery?

If not great :p

**Comment by jonnybrian** [comment]
@rcar1115 can we just hide the thumbnail and only display the title and description? push the title and description into the vertical centre kinda thing...?

**Comment by raulfelix** [comment]
@jonnybrian sure will do that.
