### ISSUE TITLE
easier editing of images in large galleries

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#177]
@rcar1115 I think you already looked into this, but the boys are asking about anything that can be done to make reordering/managing images in large galleries easier in wordpress? potentially something that serves up the thumbs in a grid style module like the media library view for instance?

**Comment by raulfelix** [comment]
@jonnybrian cannot be done with the current plugin. What it gives you now is as good as that experience can get.

To do anything it would involve ditching that plugin and perhaps trying to use the new Wordpress gallery which just came about very recently... But we would then need to go back and update all existing galleries as they use different database storage mechanisms...
