### ISSUE TITLE
Implementing eDM template

### ISSUE THREAD

**Issue by raulfelix** [lifewithoutandy/warhol#179]
The template will allow users to do the following:
- create repeated feature article rows
- create repeated news article rows with 2 items per row

**Comment by jonnybrian** [comment]
@raulfelix lovely jubbly...

feedback includes 
- [x] can you provide thumbnail ratios at 16:9 (600x338 and 280x158)
- [x] the overall width of the two column rows should be the same width as the one-column feature rows
- [x] can you make the links in the footer black underlined

**Comment by raulfelix** [comment]
@jonnybrian I have updated those items you mentioned.

**Comment by jonnybrian** [comment]
@raulfelix bud there is a second version of the ai file in dropbox with two updates, if you'll be so kind:
- [ ] an updated footer layout 
- [ ] larger logo in the header

no more after this... promise!

**Comment by raulfelix** [comment]
@jonnybrian sent you a test. Check it out and then tick that shit off ;)

**Comment by jonnybrian** [comment]
@raulfelix only thing i noticed is the copyright line is missing from the pink bar in the footer...

**Comment by jonnybrian** [comment]
@raulfelix also we need to maybe re-test that template, i noticed gmail on iPhone the footer has gone bonkers... buts let's discuss when you're in at Kippax Studio

**Comment by raulfelix** [comment]
The template may sit a little better if the background was uniformly white or grey between the featured and news sections @jonnybrian
