### ISSUE TITLE
Instabinge layout component

### ISSUE THREAD

**Issue by raulfelix** [lifewithoutandy/warhol#19]
This should allow for thumbs to sit side by side and extend beyond the grid and viewport boundaries.
Implement a script for horizontal scrolling of elements that are sitting off-canvas. 

Actual Instagram API integration is to be covered in another [task](https://github.com/lifewithoutandy/warhol/issues/20)

**Comment by raulfelix** [comment]
@jonnybrian what is the behaviour when you click the arrow in the slider? moves 1 image along or moves the whole set across and shows the next 4?

**Comment by jonnybrian** [comment]
@rcar1115 hi mate! I'd say moves next 4, but we have to be mindful that it wont be displaying 4 at all times across different breakpoints

**Comment by jonnybrian** [comment]
...so it's moving 'x'

**Comment by raulfelix** [comment]
amigo!!! :) thanks bud. No worries it is sorted.
