### ISSUE TITLE
Instabinge API integration

### ISSUE THREAD

**Issue by raulfelix** [lifewithoutandy/warhol#20]
Pull in the posts from users following LWA through the use of the [instagram API](http://instagram.com/developer/). 

This should be carried out as a separate non-blocking request on page load.

@jonnybrian Can you confirm how this works please

**Comment by jonnybrian** [comment]
Sorry @rcar1115, can you be more specific... what behaviours/details do you require?

**Comment by raulfelix** [comment]
My bad... @jonnybrian 

What is pulled in exactly? the first post from people following lwa or just posts tagged "@lifewithoutandy"?

**Comment by jonnybrian** [comment]
@rcar1115 its meant to be all the posts from the instagram members that @lifewithoutandy follow

**Comment by raulfelix** [comment]
Does "@username" link to the image on instagram @jonnybrian 
Also can we return say 40 images and leave it at that maximum?

**Comment by raulfelix** [comment]
The current behaviour we have is that about 20 posts are loaded initially. Low res images are favoured due to load time. When the user reaches the end of the horizontal paging the next set of images are loaded and paging can continue.
