### ISSUE TITLE
Icons asset format?

### ISSUE THREAD

**Issue by raulfelix** [lifewithoutandy/warhol#21]
@jonnybrian will you be creating an icon font pack for the icons?

**Comment by jonnybrian** [comment]
@rcar1115 yes buddy, here is the first version of the iconfont... its been a while since I exported one of these so i may need to supply it to you slightly differently. Let me know champ...

**Comment by jonnybrian** [comment]
@rcar1115 is it possible to attach .zip files in github somewhere?

**Comment by raulfelix** [comment]
No you cannot attach files. You will have to email that one to me @jonnybrian

**Comment by jonnybrian** [comment]
I've added a new 'assets' folder to our LWA dropbox folder... @rcar1115
