### ISSUE TITLE
Define hover states

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#24]
I need to supply this info for text, buttons, icons and dropdowns

**Comment by raulfelix** [comment]
please also include the hover state for the back to top row @jonnybrian

**Comment by jonnybrian** [comment]
@rcar1115 I've also added a sketch file to dropbox for the back to top.

Its changes slightly to fall inline with other buttons, it has a rounded corner outline now, so check the font size matches other buttons. Hover state included in dropbox sketch file
