### ISSUE TITLE
Supply design for Info page

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#25]
@rcar1115 I'm yet to deliver this, it'll be a static page containing:
- contact information
- contributor information
- about information
  Low priority for content to be administered by them.

**Comment by jonnybrian** [comment]
![info](https://cloud.githubusercontent.com/assets/7110827/3182112/31505430-ec4b-11e3-9a8b-8afaba1ee812.png)

**Comment by raulfelix** [comment]
- what colour is the header and thumbnail overlay? @jonnybrian 
- a gravatar account is required for pulling in profile pictures.

**Comment by jonnybrian** [comment]
@rcar1115 why is this the way to go? https://en.gravatar.com/

**Comment by raulfelix** [comment]
because it is built in to Wordpress which means less dev time for myself.

**Comment by jonnybrian** [comment]
@rcar1115 i've added one for myself through gravatar as you can see in the page. use my profile for now for building out the profile page. I'll chase the boys to upload their content again.

**Comment by raulfelix** [comment]
probably only worth them doing the profile stuff on the staging server @jonnybrian

**Comment by jonnybrian** [comment]
@rcar1115 can you check the mobile version of this, there needs to be space between header and title
