### ISSUE TITLE
Style the Shopify page

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#26]
@rcar1115 we will need to update their shopify page which will include a new:
- header
- fonts

But no changes to page functionality required.

**Comment by jonnybrian** [comment]
![shop-skin-example](https://cloud.githubusercontent.com/assets/7110827/3182108/1d094ac2-ec4b-11e3-8b89-52ac93a1b8e6.png)

**Comment by raulfelix** [comment]
I am not sure how I get access to change the styles of the shopify page @jonnybrian

**Comment by raulfelix** [comment]
you may need to add the shopify url to the font deck settings @jonnybrian 

http://lifewithoutandy.myshopify.com/

Also can you please review what I have done so far... there are a couple other pages too that you should make sure are ok.

**Comment by jonnybrian** [comment]
ok so i've added this domain to the fonts...

remind me again how i can take a look at the newly styled shop? @rcar1115

**Comment by raulfelix** [comment]
1. Login 
2. Go to themes
3. Click preview for this theme: Life Without Andy V.02 @jonnybrian
