### ISSUE TITLE
Create two post types and each category page

### ISSUE THREAD

**Issue by raulfelix** [lifewithoutandy/warhol#36]
###### Posts

Consist of two different types:
- Featured articles &
- News articles
###### Category

Each post will belong to **1** category 
- Twentyfour
- Tuesdays 
- Parties & Bullshit or 
- News

Within the category a post will then associate **1** tag such as fashion.
## Implementation

Within Wordpress create a "Featured posts" screen in the admin panel where all feature articles will live. Separate to that we will then have normal posts which are used for everything else. 

The featured posts will then have to be accessed with a URL such as www.lwa.com/featured/some-post-name as per the wordpress convention.  

No limit will be imposed on the number of categories or tags that can be added to articles this will have to be managed by the client.

@jonnybrian can you give the thumbs up that this approach makes sense please.

**Comment by jonnybrian** [comment]
It think the url path might need to be more like:

www.lwa.com/tuesdays/some-post-name
www.lwa.com/news/fashion/some-post-name

Then the 'featured' thing is used to define the categories in the admin...

**Comment by raulfelix** [comment]
So they will check category 'featured' as well as 'tuesdays' for instance to mark the article as a featured article then?

**Comment by jonnybrian** [comment]
I see them having two different post template types, so when they are populating a featured post template, the only category options they will have are Tuesdays, Parties & Bullshit and TwentyFour for example...

Lets chat about this so we are both clear in a hangout @rcar1115

**Comment by raulfelix** [comment]
The way we currently have it set up is:

Two post types.

##### Featured (/featured/category/post_name)

Feature articles will display only the related categories associated with it such as Tuesdays without, Parties & Bullshit etc

##### News (/news/category/post_name)

Feature articles will display only the related categories associated with it such as Fashion, Music etc

Each post type has its own section in the admin panel.
