### ISSUE TITLE
create dropdown open state

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#37]
will send this over in a .sketch file asap

**Comment by raulfelix** [comment]
poke @jonnybrian please don't forget to give me this

**Comment by raulfelix** [comment]
Dropdown state has been created. We just now need to refine look and feel

**Comment by jonnybrian** [comment]
@rcar1115 sketch file 'LWA-open-dropdown.zip' added to dropbox assets folder. Simply turn the 'SORT open' folder on and off in the layers to see the dropdown...

The icon-dropup should already exist in the iconfont.

The pink text illustrates the item in focus.
Pink will also be used for hover states for text in the dropdown list.
