### ISSUE TITLE
supply a loading wheel

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#42]
@rcar1115 this will be needed for any ajax based loading... can you indicate the right format you'd like this supplied bud?

**Comment by raulfelix** [comment]
This depends on which browsers we intend to support.

**Comment by jonnybrian** [comment]
@rcar1115 I've taken the loading wheel from here: http://preloaders.net/en/circular

I have the option for a couple of formats, I've ticked all the boxes to give you a choice, I'll upload the assets to dropbox.

Specs as follows:

Display as 32x32px for desktop... I have supplied the gif sprite at 64px so it will look right on retina displays.

**Comment by raulfelix** [comment]
So can how do we want to use this then? On the buttons for the home page? @jonnybrian Try the test site "load more features" button. you should see an example of a spinner I added for that. 

I am not sure this is the best format for the spinner... it packs a lot of JS with it for something simple. Might be better to just create an animated gif....

**Comment by jonnybrian** [comment]
@rcar1115 ok homeboy i've added a .gif version to dropbox assets, knock yourself out son.

The button loader is looking good. I think we need to add a 'loading' state to the button while the wheel is displayed, for feedback purposes. Can you try keeping the button filled, but knock the alpha back to 50% while the wheel is displayed?

**Comment by jonnybrian** [comment]
@rcar1115 I have added a white version of the loading wheel to dropbox

**Comment by raulfelix** [comment]
@jonnybrian it looks like that loading wheel does not have a transparent background. Its appearing as a white square?

**Comment by jonnybrian** [comment]
I've updated with another @rcar1115

**Comment by raulfelix** [comment]
are you sure i dont see it man @jonnybrian maybe you can attach it here cause it is an image

**Comment by jonnybrian** [comment]
its in dropbox called 3-white.gif

I've added it here below in this comment even though you cant see it... ;)
![3-white](https://cloud.githubusercontent.com/assets/7110827/3307447/a1530018-f66c-11e3-9b4d-b9b6a554cef0.GIF)

**Comment by raulfelix** [comment]
sorry bud!!! its still a white square. Tried both one from dropbox and this one. Dropbox says you didnt update it though https://www.dropbox.com/revisions/LWA/assets/3-white.GIF?_subject_uid=45482066 unless you gave the file a different name. What shall we do @jonnybrian ?

**Comment by jonnybrian** [comment]
@rcar1115 I've added a black one into dropbox, use that on pink backgrounds
