### ISSUE TITLE
supply a shop banner for home carousel  

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#43]
I'll push the client for what this should include, ideally it will include the same assets as all other features in the carousel, i.e. Title, Description, Category and background image which links.

I'll also push them to think of any other content/offers/announcements which could appear also in this space @rcar1115

**Comment by jonnybrian** [comment]
@rcar1115 we need to get this set up asap also. it will link to the shop homepage obviously. Where it sits in the order of the carousel is up for debate, you tell me how much control they will have.
- Category = Shop
- Image = uploaded at feature image size
- Title = Something
- Description = we'll need this too...

**Comment by raulfelix** [comment]
I guess we could create a "shop" post type. If I ask my lucky :8ball: it tells me that they may have more than one shop banner in future?? @jonnybrian 

This would behave the same as creating a featured or news post except there would be no need to choose a "shop" category as it is implied. At the moment there is no way to control ordering in the carousel it is just based chronologically on the order in which posts are added. The options to manage this would be:
- always make sure that shop posts appear last in the carousel
- allow them to enter an index number for the position in the carousel (more work and possibly not very user friendly)

**Comment by raulfelix** [comment]
@jonnybrian I have added the new shop banner post type... Give it whirl

**Comment by jonnybrian** [comment]
@rcar1115 loving it mate!! I see you've set it to open new window... i guess thats the way to go...? hmmm yes, lets leave it for now and close this fella...

**Comment by raulfelix** [comment]
It is really easy to change if you want it to open in same window @jonnybrian
