### ISSUE TITLE
Implement news category template logic

### ISSUE THREAD

**Issue by raulfelix** [lifewithoutandy/warhol#47]

**Comment by raulfelix** [comment]
@jonnybrian does the news category page such as news/top-10 have the featured section? or do we drop that little "featured" label above the title.

**Comment by jonnybrian** [comment]
Are you referring to the 'latest' post at the top of a category view? See below... if so, then maybe our 'featured' label should say 'Latest'... Ja?

![category-large](https://cloud.githubusercontent.com/assets/7110827/2872074/351338f4-d340-11e3-9731-c7e154eb484b.jpg)

**Comment by raulfelix** [comment]
yes that is what i was talking about @jonnybrian because the news section doesnt have a "featured" post. Ok will make it "Latest" unless otherwise instructed
