### ISSUE TITLE
Implement copy URL to clipboard

### ISSUE THREAD

**Issue by raulfelix** [lifewithoutandy/warhol#52]
This task is TBD as it requires a few dependencies in order to work...

**Comment by raulfelix** [comment]
Would be good if this was just an input that had the text already highlighted and then perhaps a small bit of text saying something like windows: ctrl+c mac: cmd+c to copy. 

Reason being there is no way to copy text to system clipboard through JS due to security. It has been done in the past through the use of flash cause you have to manually install flash hence it passes security but this does not translate to mobile.

Can we keep it simple @jonnybrian

**Comment by jonnybrian** [comment]
@rcar1115 ok so what you're saying here is we shouldn't support the 'Copy URL' button...

I'd keep it super simple and simple offer up the URL in the input field... I mean do we really even need the input field if its going to truncate? Shall we just offer up the URL as a full text string, with no instructions on how to copy?

Yes do that thanks...

**Comment by raulfelix** [comment]
yes that is what I am saying.

What we could do is leave it in the text field, remove the "copy url" button and highlight the text when the field gets focus leaving one last step for the user to just copy the text rather than needing to highlight it.

**Comment by raulfelix** [comment]
I have made it highlight on click. We can create another task if this is not what you want to leave it as @jonnybrian
