### ISSUE TITLE
Implement the author/photos by content management

### ISSUE THREAD

**Issue by raulfelix** [lifewithoutandy/warhol#58]
The part that says: "Words by warhol , Photos by Mitchel" in an article.
- How do you want to manage that? Raw text field in meta box?
- What should it actually say?

**Comment by jonnybrian** [comment]
@rcar1115 I think we need separate fields in admin after the article WYSIWYG:
- Words
- Photos

The author only has to enter the name, your clever bit adds the pre-pended label "Words by..." etc
The dot dividing the two is automatic also.

If the field is empty no value is displayed.

Happy with that? If too involved please say and we can think of something easier to implement.

**Comment by raulfelix** [comment]
If a user signs up to this wordpress account they will not need to enter their name as this is pulled from their profile. Do you want to use that default behaviour or still manually get them to add something in a words field? @jonnybrian

**Comment by jonnybrian** [comment]
I think we need to keep it manual as there will be times where the authenticated author is not the actual author that deserves crediting @rcar1115 

without complicating things, what if the authors were available in a dropdown?

**Comment by raulfelix** [comment]
Ok no problem... I think that is called plagiarism ;)
