### ISSUE TITLE
Disable inline gallery on mobile

### ISSUE THREAD

**Issue by raulfelix** [lifewithoutandy/warhol#59]
We need to clarify whether this is not an option on touch or just below say bp2? @jonnybrian

**Comment by jonnybrian** [comment]
we agreed that this is to be disabled for which ever our mobile breakpoint is.... @rcar1115

**Comment by raulfelix** [comment]
When disabling will then look for a featured image to use as the background or the first image in the gallery?? @jonnybrian

**Comment by jonnybrian** [comment]
First image in the gallery would be the most consistent answer, but the format of that first gallery image is not the same as a feature image... hmmm.

This then mandates that every gallery must have a feature image... hmmm.

OK yes lets do that... take the feature image, and I'll mandate that every gallery must have a feature image. @rcar1115
