### ISSUE TITLE
homepage carousel arrow positions

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#65]
I intended for the arrows to sit at the edge of the grid, take a look at the designs for the homepage and you'll see what I mean.

The header and description should have a max width of 8 columns.

**Comment by raulfelix** [comment]
I assume the description in the footer is set at the same max-width of 8 columns @jonnybrian ?

**Comment by raulfelix** [comment]
I set the footer text to have the same 8 column width. We can raise another bug if its wrong :p
