### ISSUE TITLE
refine loading of a feature image or gallery

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#66]
@rcar1115 we will need to work on the loading of a feature image when an article loads. it'll need a loading wheel and some fading in of the image etc, so lets go through this together when we are ready to refine.

**Comment by raulfelix** [comment]
This is actually a very involved task so if you can give me an idea of how it should work that would be great. For example:
- Should the text be visible while the image is loading?
- If so for the feature image what colour should the background and text while loading?
- Where should the loading wheel appear?

This will also require browser compatibility work so if you can give me the info before hand it will make tweaking easier later @jonnybrian

**Comment by raulfelix** [comment]
- Hide the text while loading and show the loading wheel.

**Comment by jonnybrian** [comment]
@rcar1115 does this issue need to be extended to include the home carousel, or is that mentioned somewhere else? 

Specs for this are please a black background while loading, no text, and a loading wheel in the centre of the space.

**Comment by raulfelix** [comment]
@jonnybrian This can cover the home page carousel too. OK so:
- I will add a black background for loading of carousel, gallery and features images.
- we will use the white loader

Do carousel items with no images keep the pink background with white text?

**Comment by jonnybrian** [comment]
Yes pink bg and white text... but of course only after loading has occurred... @rcar1115

**Comment by raulfelix** [comment]
So I have completed the carousel. Please review @jonnybrian

**Comment by jonnybrian** [comment]
@rcar1115 i've added a refinement task https://github.com/lifewithoutandy/warhol/issues/106 which is to do with hovers etc, to complete on Thursday.... this one is getting closed.
