### ISSUE TITLE
typographic styles in WYSIWYG

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#72]
Styles for article content we will need something simple like this to start with:

Intro paragraph
Header
Subhead
Paragraph
Block quote

The details of which we can tweak in our final round of polish, but if you can create/modify the dropdown that will do this, that'd be awesome...

**Comment by raulfelix** [comment]
I have updated the dropdown to have the values you have requested. Of course they need to be refined as they are randomish... lets talk about this refinement process...
