### ISSUE TITLE
Implement the author page

### ISSUE THREAD

**Issue by raulfelix** [lifewithoutandy/warhol#73]
Awaiting the design for this page. For the moment I will dump out the information including:
- name
- link to website if any
- bio
- profile pic
- and all posts by the author selected

**Comment by jonnybrian** [comment]
@rcar1115 see attached design

![profile](https://cloud.githubusercontent.com/assets/7110827/3353945/4fa77a6c-fa92-11e3-9d0a-bde069738192.png)

**Comment by raulfelix** [comment]
implemented and ready to review @jonnybrian
