### ISSUE TITLE
Notes for Saturday - 140612

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#75]
~~Remove gradient for News articles featured in homepage carousel #78~~

~~Develop the way we can embed responsive videos something like this: https://wordpress.org/plugins/advanced-responsive-video-embedder/
Add video thumb to gallery manually for News posts with video only and no feature image or post #79~~

Customise the default play button overlay - if this is possible https://github.com/lifewithoutandy/warhol/issues/81

Switch to their server before they start the uploads https://github.com/lifewithoutandy/warhol/issues/80

~~Create accounts for each user in WP before Saturday~~

**Comment by jonnybrian** [comment]
@rcar1115 there seems to be an error when you add a video news post with no feature image to the home carousel. no pink background appears...

**Comment by raulfelix** [comment]
Ahhh yeah because i removed the pink background so you could see the spinner. Ill fix that @jonnybrian

**Comment by jonnybrian** [comment]
I need to supply you a white spinner
