### ISSUE TITLE
link to LWA Facebook account and integrate Like

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#77]

**Comment by raulfelix** [comment]
@jonnybrian I have used the existing facebook app id from the legacy lifewithoutandy.com site. So for now no need to setup another.

**Comment by jonnybrian** [comment]
@rcar1115 can we close this then?

**Comment by raulfelix** [comment]
Yeah lets close and open a bug if there are any issues but this should be fine @jonnybrian
