### ISSUE TITLE
Header carousel

### ISSUE THREAD

**Issue by raulfelix** [lifewithoutandy/warhol#8]
Integrate a responsive, touch enabled carousel and implement the styles for all screen sizes. Should allow for swiping on devices.

**Comment by raulfelix** [comment]
Can you please let me know what kind of effect you are expecting as you move from one image to the next in the carousel @jonnybrian?

**Comment by jonnybrian** [comment]
@rcar1115 the fading of images is good, however we will add movement to the title and description during the final round of polish
