### ISSUE TITLE
Adding watermark graphic to images uploaded to the gallery

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#85]
@rcar1115 this came up on the meeting on Saturday. a semi-transparent png graphic to sit over each image upon image upload?

Is this possible? Is there a better way to do it?

Let's discuss...

**Comment by raulfelix** [comment]
Hey @jonnybrian 

So the only way so far to achieve this is to create a custom image type which we will use to render gallery images. I have created a "watermarked" type. 

However, there is an intricacy in wordpress which is if you upload an image it will fail to produce a new image in the upload directory if one of the image dimensions of the uploaded image are equal to the new image size.

This means we need the gallery image to have a different size to actually be generated and get the watermark added to it. So i have set the height of the image to the height of the header (748px) for now to get it to generate. 

What are your thoughts so far?

**Comment by raulfelix** [comment]
From the plugins I have evaluated they all affect the quiality of the image after adding a watermark... They appear with less vibrant/bright colours. Does this matter @jonnybrian

**Comment by jonnybrian** [comment]
@rcar1115 where can i test this bud? I couldn't see any watermarks on theyardy...

**Comment by raulfelix** [comment]
I have checked in any code cause it involves changes in a few places. Lets go through this one on wednesday together.

**Comment by jonnybrian** [comment]
@rcar1115 I've pushed this one back onto the client, so for now will close this issue...
