### ISSUE TITLE
Add category logo to home carousel

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#86]
@rcar1115 this is something I'll need to play with in sketch first, leave it with me...

**Comment by jonnybrian** [comment]
Just wanted to show you what I was thinking about here... its not signed off yet, but I want to check this is not going to cause problems. It would only be displayed here on the home carousel

![home-large-redbull](https://cloud.githubusercontent.com/assets/7110827/3296602/503434b8-f5e0-11e3-9e4e-eb5414f8f037.png)

**Comment by raulfelix** [comment]
That should be OK.

**Comment by jonnybrian** [comment]
@rcar1115  ok lets go for this... 
- Use the 'close' icon for the cross
- Pull in the logo from the corresponding category page. 
- Please scale the logo down 50% in size from how its displayed on the category page.

Make sense...?

**Comment by raulfelix** [comment]
Oui. 

And only the category name is clickable or the whole of it? At the moment there is a pink hover on the category @jonnybrian

**Comment by raulfelix** [comment]
This has been implemented and is ready for review @jonnybrian

**Comment by raulfelix** [comment]
Is there any more work to be done on this sponsor logo in carousel? @jonnybrian
