### ISSUE TITLE
The category header colour overlay module not displaying

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#87]
@rcar1115 none of the boys on Saturday could see that module in wp admin... they are all set as administrators so I dont know why that was the case but we need to investigate...

**Comment by raulfelix** [comment]
@jonnybrian ok I am not sure. I have created a user with role administrator and I can see it. Make sure they are not set as author. The module for me was below the text editor in case it just got overlooked? Can you double check please.

**Comment by jonnybrian** [comment]
I just logged in as mitch-r and you're right, its under the text editor...

**Comment by raulfelix** [comment]
just let them know they can drag and re-arrange those panels @jonnybrian
