### ISSUE TITLE
refine next/prev for modal instabinge

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#89]
@rcar1115 i'm keen to see a next/prev transition of the entire panel sliding left/right... please flag any potential concerns here. The animation should be quick and snappy with a minor bit of easing...

One question this raises is whether we should do the same for the modal gallery too...??? If you don't think performance is a concern, and its not a totally bitch to implement then let's go for it...

**Comment by raulfelix** [comment]
Set description on bp1 to
font-size: 12px;
line-height: 1.5;

**Comment by raulfelix** [comment]
@jonnybrian I have improved the performance of the modal view so I think we may be all good here... There are still some improvements I can make which I have listed as part of the https://github.com/lifewithoutandy/warhol/issues/125 backlog task. But we should be able to close this one.

**Comment by jonnybrian** [comment]
There seems to be some new behaviour to the desktop breakpoint which is not ideal @rcar1115 

Where now the modal images are set to 'drag' can we remove this and only use the arrows to advance?

**Comment by raulfelix** [comment]
how did that happen!!!! :O 

Done. Please verify this one on staging @jonnybrian

**Comment by jonnybrian** [comment]
@rcar1115 wow, this is a thing of beauty! Working super nicely bud... well done!!

We will need to tweak slightly the bp3 tablet portrait view for modal, but will address this as part of that refinement work. I'll create an issue now and list a few things out.

**Comment by jonnybrian** [comment]
i just noticed this is still advancing when clicking anywhere inline with the panel @rcar1115 can you remove that behaviour thanks...

**Comment by raulfelix** [comment]
@jonnybrian removed.
