### ISSUE TITLE
Header gallery 

### ISSUE THREAD

**Issue by raulfelix** [lifewithoutandy/warhol#9]
This may require a custom script served only to the pages a header gallery exists on.

**Comment by raulfelix** [comment]
@jonnybrian can you please refresh my memory on how this works in each scenario.

Is there only a modal view? or is the gallery inline? Also I dont think you have ever shown me a thumbnail view design

**Comment by jonnybrian** [comment]
@rcar1115 below are a couple of states showing the inline version of the gallery header for desktop and everything before mobile. We talked a bit early on about removing the inline below a certain breakpoint as the crop messes up landscape images. 

For those lower breakpoints (mobile) we'd force the user to only view modally, but for everythign else they have the choice to have inline or modal. Again happy to discuss this with you in more detail as part of the whole gallery functionality.

![header-gallery-01](https://cloud.githubusercontent.com/assets/7110827/2872049/a8f9648a-d33d-11e3-9bf7-96787b10a240.png)
![header-gallery-02](https://cloud.githubusercontent.com/assets/7110827/2872050/a8f9c0e2-d33d-11e3-8aff-6b9ca643249e.png)

**Comment by jonnybrian** [comment]
@rcar1115 apologies the thumbview may have been missed off the elements sketch files I sent. 

Below shows what I intended for the thumbs when in the inline view. When the thumbs are revealed, the page content is pushed down as a slide transition. The thumb icon toggles the thumbs in and out. The pink bar indicates the thumb in focus. Mouse hover over right edge slides images to the left etc...

At this stage I have not got a design for the modal version of this, again I want to discuss this with you together so we implement what makes most sense...

![gallery - large](https://cloud.githubusercontent.com/assets/7110827/2872067/5c275d54-d33f-11e3-89d2-58a11dc18131.png)

**Comment by raulfelix** [comment]
So for the inline view do we only show the title and not the subtitle? or both? @jonnybrian

**Comment by raulfelix** [comment]
Are you sure you want the thumbnails to move based on where the user hovers. That is different to the instabinge thumbnails? @jonnybrian It would simplify things for me if it just had left and right arrows for controls. Also for determining behaviour on mobile...

**Comment by jonnybrian** [comment]
Go ahead and use the same behaviours as the carousel for Instabinge... good point @rcar1115

**Comment by raulfelix** [comment]
I think this is most of the way there. We will cover off anything else as part of #23
