### ISSUE TITLE
adjust sensitivity of swipes on touch devices

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#90]
@rcar1115 let's discuss the options we have here. on iOS its really hard to only progress one image at a time, its too sensitive... do we have control here?

**Comment by raulfelix** [comment]
We have a bit of control with the plugin but not a huge amount... I have adjusted the sensitivity for the gallery and instabinge carousel. Please retry @jonnybrian

**Comment by jonnybrian** [comment]
@rcar1115 seems to be waaay better... i'm closing this
