### ISSUE TITLE
loading wheel spinning backwards

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#91]
Not sure whats going on here @rcar1115 but I tested the gallery loading in the header and the wheel is spinning backwards slowly... thoughts?

**Comment by raulfelix** [comment]
I haven't seen it happen and I don't control the spinning it is just the animated gif which I hide and reveal @jonnybrian so im not sure but ill keep an eye out

**Comment by jonnybrian** [comment]
Also I notice the pink wheel on black is looking bad as there are white pixels anti-aliasing off the pink creating a white outline due to the transparent bg... I'll keep this issue open and look into something cleaner.

To recap, can you confirm we have two types of loader currently:
- pink loader on black bg
- black loader on pink bg

any other scenario floating round @rcar1115 ?

**Comment by raulfelix** [comment]
Indeed it looks shite.

Havent implemented the black bg uniformly yet.

One other case is loading of instagram modal images has the pink loader on white background @jonnybrian

**Comment by raulfelix** [comment]
The other thing we can do JB is you give me a png of the loader and I will use css to animate it. We will still need to fall back to the gif for browsers that dont support transforms @jonnybrian It can even be an icon font added to the pack you already supplied

**Comment by jonnybrian** [comment]
I've not seen this happen again since last week so lets leave it... But when you're in on Thursday I'll possibly look to replace the pink gif with something cleaner... @rcar1115

**Comment by raulfelix** [comment]
@jonnybrian fucking spinner is live... for real

**Comment by jonnybrian** [comment]
@rcar1115 what a thing of beauty!!! Thats the original one i supplied earlier today yeah? Love it! Well done mate!!
