### ISSUE TITLE
inline gallery hover of next/prev image

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#92]
when you hover the arrow the next/prev image hover state should remain hovered... make sense @rcar1115 ?

**Comment by raulfelix** [comment]
This most likely will not be possible as the arrows are independent DOM elements in order to float over the gallery @jonnybrian

**Comment by jonnybrian** [comment]
ok... its not a massive problem but a little disorientating... see for yourself... any other suggestions? maybe we make the impact a little less jarring by turning down the different alpha values... what are they currently?

**Comment by raulfelix** [comment]
the alphas are initially at 0.6 and on hover go to 0.4

**Comment by jonnybrian** [comment]
@rcar1115 lets drop the hover to 0.5 please bud
