### ISSUE TITLE
News subcategory titles adjusted on category pages

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#93]
See design below which shows the sub category as the main title in the header, with the description underneath

![category-news](https://cloud.githubusercontent.com/assets/7110827/3295451/8f288f54-f5c0-11e3-8194-d4c02eea947d.png)

**Comment by raulfelix** [comment]
At the moment if you view a category you can add a description. This is what is being used for news post type categories. @jonnybrian updated test server so you can see this.

**Comment by jonnybrian** [comment]
That's now looking fab @rcar1115, problem is I can't see how to add the sponsor logo and bg image to these pages, which makes me think its not built that way yet...? My bad, maybe some crossed wires here? These News sub-categories also need the same functionality as the feature categories for sponsors.

**Comment by raulfelix** [comment]
I recall i checked with you when doing the initial build that is was only the main areas of the app that exist as pages that would be sponsored. Not every category they could create would allow this. Is this something new after your recent meeting?

**Comment by jonnybrian** [comment]
No its not new unfortunately... which is why I have a nasty feeling I've not been clear in the briefing... How big a deal is it? I feel like I've ruined your day... :/

**Comment by raulfelix** [comment]
ohhhhhhhhh OK. Its not trivial. Not sure yet.

**Comment by raulfelix** [comment]
ok so....

If I customise the category edit screen to allow you to upload a feature image and a logo as well as define the opacity/colour of the overlay would that be sufficient for to cover this off? @jonnybrian 

I may then try and remove the need for pages for "parties & bs", "twentyfour" etc so that they are all managed in the same way?

**Comment by raulfelix** [comment]
What should happen with the "News" landing page header?? @jonnybrian

**Comment by jonnybrian** [comment]
Same deal as the rest @rcar1115 , the ability to sponsor it, but then the content below is an aggregation of all news... do that pose problematic?

**Comment by raulfelix** [comment]
I just wanted to confirm it was the same is all. Thanks @jonnybrian
