### ISSUE TITLE
investigate fontdeck issue with chrome

### ISSUE THREAD

**Issue by jonnybrian** [lifewithoutandy/warhol#94]
@rcar1115 is fontdeck for the Apercu Pro font?

**Comment by raulfelix** [comment]
I think so.

What the aim should be here is to have only one remote server loading the fonts as this a blocking IO operation which increases page load time. Ideally you serve the fonts up locally in your app like the icons... this is the best solution. The next best choice would be to use one font provider only for all the fonts you want to use.

**Comment by raulfelix** [comment]
@jonnybrian I have been investigating and it appears that Safari and Chrome will refrain from displaying text set in a web font until the font has loaded, while Internet Explorer won’t show anything on the page until the font loads. Meanwhile, Firefox will display the site with the fallback fonts in the font stack, and then switch to the linked fonts after they’ve finished loading.

So at this point there isnt much i can do bud.

**Comment by jonnybrian** [comment]
I thought we are talking about when the page 'hangs' in chrome for an infinity... @rcar1115 

Not the default-to-webfont jump...
